---
openapi: 3.1.0
info:
  title: Attio API
  version: 2.0.0
  contact:
    name: Attio Support
    email: support@attio.com
    url: https://attio.com/help
tags:
- name: Objects
  description: Objects are the core data models inside of Attio. They contain standard
    objects, such as [people](/docs/standard-objects-people), [companies](/docs/standard-objects-companies)
    or [deals](/docs/standard-objects-deals), and custom objects that are specific
    to your use-case. See our [data model guide](/docs/data-model) for more information.
- name: Attributes
  description: Attributes model properties of objects and lists. Some attributes,
    such as the `name` attribute on a person, are system-defined, while others are
    user-defined. Attributes are one of [many types](/docs/attribute-types) such as
    text, location or select. See our [data model guide](/docs/data-model) for more
    information.
- name: Records
  description: Records are individual instances of objects e.g. a specific [person](/docs/standard-objects-people)
    or [company](/docs/standard-objects-companies). See our [data model guide](/docs/data-model)
    for more information.
- name: Lists
  description: Lists are used to model a particular process. A list contains many
    records of a single object type, where each record is represented by an entry.
    Entries contain their own data from attributes defined on the list and also data
    from their parent record. See our [data model guide](/docs/data-model) for more
    information.
- name: Meta
  description: Meta endpoints are used to get information about the API token.
- name: Entries
  description: Entries are elements in a list that reference a single parent record.
    Entries contain their own data from attributes defined on the list and also data
    from their parent record. See our [data model guide](/docs/data-model) for more
    information.
- name: Workspace members
  description: Workspace members represent a user with access to a workspace. Workspace
    members are assigned roles that determine what they can do within the workspace.
- name: Notes
  description: Notes are rich text documents that reference a single parent record.
- name: Tasks
  description: A task is a defined, actionable item with references to linked records
    and assigned workspace members.
- name: Webhooks
  description: Webhooks allow you to listen for changes to data in Attio, for example
    when a record is updated.
- name: Threads
  description: Threads are groups of [comments](/reference/get_v2-comments-comment-id)
    on either a record or entry.
- name: Comments
  description: Comments are messages on a [thread](/reference/get_v2-threads).
- name: People
  description: People are one of the core objects inside of Attio. Person records
    can be added to lists and can be created automatically when syncing your mailbox.
- name: Companies
  description: Companies are one of the core objects inside of Attio. Company records
    can be added to lists and can be created automatically when syncing your mailbox.
- name: Users
  description: Users are an optional standard object that represents a user of your
    system. Users can belong to many workspaces.
- name: Deals
  description: Deals are an optional standard object that represent a deal or opportunity.
- name: Workspaces
  description: Workspaces are an optional standard object that represent a workspace
    or account in your system. Workspaces have many users and can be used to model
    a multi-tenant system. A company record can optionally have multiple workspaces.
security:
- oauth2: []
servers:
- url: https://api.attio.com
  description: Production
components:
  securitySchemes:
    oauth2:
      type: oauth2
      description: This API uses OAuth 2.0 with the authorization code grant flow.
      flows:
        authorizationCode:
          authorizationUrl: https://app.attio.com/authorize
          tokenUrl: https://app.attio.com/oauth/token
          scopes:
            user_management:read: View workspace members.
            user_management:read-write: View workspace members.
            record_permission:read: View, and optionally write, records.
            record_permission:read-write: View, and optionally write, records.
            object_configuration:read: View, and optionally write, the configuration
              and attributes of objects.
            object_configuration:read-write: View, and optionally write, the configuration
              and attributes of objects.
            list_entry:read: View, and optionally write, the entries in a list.
            list_entry:read-write: View, and optionally write, the entries in a list.
            list_configuration:read: View, and optionally write, the configuration
              and attributes of lists.
            list_configuration:read-write: View, and optionally write, the configuration
              and attributes of lists.
            public_collection:read: View, and optionally write, both the settings
              and information within public collections.
            public_collection:read-write: View, and optionally write, both the settings
              and information within public collections.
            private_collection:read: View, and optionally modify, both the settings
              and information of all collections within the workspace, regardless
              of their access settings.
            private_collection:read-write: View, and optionally modify, both the settings
              and information of all collections within the workspace, regardless
              of their access settings.
            comment:read: View comments (and threads), and optionally write comments.
            comment:read-write: View comments (and threads), and optionally write
              comments.
            task:read: View, and optionally write, tasks.
            task:read-write: View, and optionally write, tasks.
            note:read: View, and optionally write, notes.
            note:read-write: View, and optionally write, notes.
            webhook:read: View, and optionally manage, webhooks.
            webhook:read-write: View, and optionally manage, webhooks.
paths:
  "/v2/objects":
    get:
      summary: List objects
      description: |-
        Lists all system-defined and user-defined objects in your workspace.

        Required scopes: `object_configuration:read`.
      tags:
      - Objects
      security:
      - oauth2:
        - object_configuration:read
    post:
      summary: Create an object
      description: |-
        Creates a new custom object in your workspace.

        Required scopes: `object_configuration:read-write`.
      tags:
      - Objects
      security:
      - oauth2:
        - object_configuration:read-write
  "/v2/objects/{object}":
    get:
      summary: Get an object
      description: |-
        Gets a single object by its `object_id` or slug.

        Required scopes: `object_configuration:read`.
      tags:
      - Objects
      security:
      - oauth2:
        - object_configuration:read
    patch:
      summary: Update an object
      description: |-
        Updates a single object. The object to be updated is identified by its `object_id`.

        Required scopes: `object_configuration:read-write`.
      tags:
      - Objects
      security:
      - oauth2:
        - object_configuration:read-write
  "/v2/{target}/{identifier}/attributes":
    get:
      summary: List attributes
      description: |-
        Lists all attributes defined on a specific object or list. Attributes are returned in the order that they are sorted by in the UI.

        Required scopes: `object_configuration:read`.
      tags:
      - Attributes
      security:
      - oauth2:
        - object_configuration:read
    post:
      summary: Create an attribute
      description: |-
        Creates a new attribute on either an object or a list.

        To create an attribute on an object, you must also have the `object_configuration:read-write` scope.

        To create an attribute on a list, you must also have the `list_configuration:read-write` scope.
      tags:
      - Attributes
      security:
      - oauth2: []
  "/v2/{target}/{identifier}/attributes/{attribute}":
    get:
      summary: Get an attribute
      description: |-
        Gets information about a single attribute on either an object or a list.

        Required scopes: `object_configuration:read`.
      tags:
      - Attributes
      security:
      - oauth2:
        - object_configuration:read
    patch:
      summary: Update an attribute
      description: |-
        Updates a single attribute on a given object or list.

        Required scopes: `object_configuration:read-write`.
      tags:
      - Attributes
      security:
      - oauth2:
        - object_configuration:read-write
  "/v2/{target}/{identifier}/attributes/{attribute}/options":
    get:
      summary: List select options
      description: |-
        Lists all select options for a particular attribute on either an object or a list.

        Required scopes: `object_configuration:read`.
      tags:
      - Attributes
      security:
      - oauth2:
        - object_configuration:read
    post:
      summary: Create a select option
      description: |-
        Adds a select option to a select attribute on an object or a list.

        Required scopes: `object_configuration:read-write`.
      tags:
      - Attributes
      security:
      - oauth2:
        - object_configuration:read-write
  "/v2/{target}/{identifier}/attributes/{attribute}/options/{option}":
    patch:
      summary: Update a select option
      description: |-
        Updates a select option on an attribute on either an object or a list.

        Required scopes: `object_configuration:read-write`.
      tags:
      - Attributes
      security:
      - oauth2:
        - object_configuration:read-write
  "/v2/{target}/{identifier}/attributes/{attribute}/statuses":
    get:
      summary: List statuses
      description: |-
        Lists all statuses for a particular status attribute on either an object or a list.

        Required scopes: `object_configuration:read`.
      tags:
      - Attributes
      security:
      - oauth2:
        - object_configuration:read
    post:
      summary: Create a status
      description: |-
        Add a new status to a status attribute on either an object or a list.

        Required scopes: `object_configuration:read-write`.
      tags:
      - Attributes
      security:
      - oauth2:
        - object_configuration:read-write
  "/v2/{target}/{identifier}/attributes/{attribute}/statuses/{status}":
    patch:
      summary: Update a status
      description: |-
        Update a status on an status attribute on either an object or a list.

        Required scopes: `object_configuration:read-write`.
      tags:
      - Attributes
      security:
      - oauth2:
        - object_configuration:read-write
  "/v2/objects/{object}/records/query":
    post:
      summary: List records
      description: |-
        Lists people, company or other records, with the option to filter and sort results.

        Required scopes: `record_permission:read`, `object_configuration:read`.
      tags:
      - Records
      security:
      - oauth2:
        - record_permission:read
        - object_configuration:read
  "/v2/objects/{object}/records":
    post:
      summary: Create a record
      description: |-
        Creates a new person, company or other record. This endpoint will throw on conflicts of unique attributes. If you would prefer to update records on conflicts, please use the [Assert record endpoint](/reference/put_v2-objects-object-records) instead.

        Required scopes: `record_permission:read-write`, `object_configuration:read`.
      tags:
      - Records
      security:
      - oauth2:
        - record_permission:read-write
        - object_configuration:read
    put:
      summary: Assert a record
      description: |-
        Use this endpoint to create or update people, companies and other records. A matching attribute is used to search for existing records. If a record is found with the same value for the matching attribute, that record will be updated. If no record with the same value for the matching attribute is found, a new record will be created instead. If you would like to avoid matching, please use the [Create record endpoint](/reference/post_v2-objects-object-records).

        If the matching attribute is a multiselect attribute, new values will be added and existing values will not be deleted. For any other multiselect attribute, all values will be either created or deleted as necessary to match the list of supplied values.

        Required scopes: `record_permission:read-write`, `object_configuration:read`.
      tags:
      - Records
      security:
      - oauth2:
        - record_permission:read-write
        - object_configuration:read
  "/v2/objects/{object}/records/{record_id}":
    get:
      summary: Get a record
      description: |-
        Gets a single person, company or other record by its `record_id`.

        Required scopes: `record_permission:read`, `object_configuration:read`.
      tags:
      - Records
      security:
      - oauth2:
        - record_permission:read
        - object_configuration:read
    patch:
      summary: Update a record
      description: |-
        Use this endpoint to update people, companies and other records by `record_id`. If the update payload includes multiselect attributes, the values supplied will be created and prepended to the list of values that already exist (if any). Use the [Assert record endpoint](/reference/put_v2-objects-object-records) to overwrite or remove multiselect attribute values.

        Required scopes: `record_permission:read-write`, `object_configuration:read`.
      tags:
      - Records
      security:
      - oauth2:
        - record_permission:read-write
        - object_configuration:read
    delete:
      summary: Delete a record
      description: |-
        Deletes a single record (e.g. a company or person) by ID.

        Required scopes: `object_configuration:read`, `record_permission:read-write`.
      tags:
      - Records
      security:
      - oauth2:
        - object_configuration:read
        - record_permission:read-write
  "/v2/objects/{object}/records/{record_id}/attributes/{attribute}/values":
    get:
      summary: List record attribute values
      description: |-
        Gets all values for a given attribute on a record. If the attribute is historic, this endpoint has the ability to return all historic values using the `show_historic` query param.

        Required scopes: `record_permission:read`, `object_configuration:read`.
      tags:
      - Records
      security:
      - oauth2:
        - record_permission:read
        - object_configuration:read
  "/v2/objects/{object}/records/{record_id}/entries":
    get:
      summary: List record entries
      description: |-
        List all entries, across all lists, for which this record is the parent.

        Required scopes: `record_permission:read`, `object_configuration:read`, `list_entry:read`.
      tags:
      - Records
      security:
      - oauth2:
        - record_permission:read
        - object_configuration:read
        - list_entry:read
  "/v2/lists":
    get:
      summary: List all lists
      description: |-
        List all lists that your access token has access to. lists are returned in the order that they are sorted in the sidebar.

        Required scopes: `list_configuration:read`.
      tags:
      - Lists
      security:
      - oauth2:
        - list_configuration:read
    post:
      summary: Create a list
      description: "Creates a new list.\n\nOnce you have your list, add attributes
        to it using the [Create attribute](/reference/post_v2-target-identifier-attributes)
        API, and add records to it using the [Add records to list](/reference/post_v2-lists-list-entries)
        API. \n\nNew lists must specify which records can be added with the `parent_object`
        parameter which accepts either an object slug or an object ID. Permissions
        for the list are controlled with the `workspace_access` and `workspace_member_access`
        parameters.\n\nPlease note that new lists must have either `workspace_access`
        set to `\"full-access\"` or one or more element of `workspace_member_access`
        with a `\"full-access\"` level. It is also possible to receive a `403` billing
        error if your workspace is not on a plan that supports either advanced workspace
        or workspace member-level access for lists.\n\nRequired scopes: `list_configuration:read-write`."
      tags:
      - Lists
      security:
      - oauth2:
        - list_configuration:read-write
  "/v2/lists/{list}":
    get:
      summary: Get a list
      description: |-
        Gets a single list in your workspace that your access token has access to.

        Required scopes: `list_configuration:read`.
      tags:
      - Lists
      security:
      - oauth2:
        - list_configuration:read
    patch:
      summary: Update a list
      description: |-
        Updates an existing list. Permissions for the list are controlled with the `workspace_access` and `workspace_member_access` parameters. Please note that lists must have either `workspace_access` set to `"full-access"` or one or more element of `workspace_member_access` with a `"full-access"` level. It is also possible to receive a `403` billing error if your workspace is not on a plan that supports either advanced workspace or workspace member level access for lists. Changing the parent [...]

        Required scopes: `list_configuration:read-write`.
      tags:
      - Lists
      security:
      - oauth2:
        - list_configuration:read-write
  "/v2/lists/{list}/entries/query":
    post:
      summary: List entries
      description: |-
        Lists entries in a given list, with the option to filter and sort results.

        Required scopes: `list_entry:read`, `list_configuration:read`.
      tags:
      - Entries
      security:
      - oauth2:
        - list_entry:read
        - list_configuration:read
  "/v2/lists/{list}/entries":
    post:
      summary: Create an entry (add record to list)
      description: |-
        Adds a record to a list as a new list entry. This endpoint will throw on conflicts of unique attributes. Multiple list entries are allowed for the same parent record

        Required scopes: `list_entry:read-write`, `list_configuration:read`.
      tags:
      - Entries
      security:
      - oauth2:
        - list_entry:read-write
        - list_configuration:read
    put:
      summary: Assert a list entry by parent
      description: |-
        Use this endpoint to create or update a list entry for a given parent record. If an entry with the specified parent record is found, that entry will be updated. If no such entry is found, a new entry will be created instead. If there are multiple entries with the same parent record, this endpoint with return the "MULTIPLE_MATCH_RESULTS" error. When writing to multi-select attributes, all values will be either created or deleted as necessary to match the list of values supplied in the req[...]

        Required scopes: `list_entry:read-write`, `list_configuration:read`.
      tags:
      - Entries
      security:
      - oauth2:
        - list_entry:read-write
        - list_configuration:read
  "/v2/lists/{list}/entries/{entry_id}":
    get:
      summary: Get a list entry
      description: |-
        Gets a single list entry by its `entry_id`.

        Required scopes: `list_entry:read`, `list_configuration:read`.
      tags:
      - Entries
      security:
      - oauth2:
        - list_entry:read
        - list_configuration:read
    patch:
      summary: Update a list entry (append multiselect values)
      description: |-
        Use this endpoint to update list entries by `entry_id`. If the update payload includes multiselect attributes, the values supplied will be created and prepended to the list of values that already exist (if any). Use the `PUT` endpoint to overwrite or remove multiselect attribute values.

        Required scopes: `list_entry:read-write`, `list_configuration:read`.
      tags:
      - Entries
      security:
      - oauth2:
        - list_entry:read-write
        - list_configuration:read
    put:
      summary: Update a list entry (overwrite multiselect values)
      description: |-
        Use this endpoint to update list entries by `entry_id`. If the update payload includes multiselect attributes, the values supplied will overwrite/remove the list of values that already exist (if any). Use the `PATCH` endpoint to add multiselect attribute values without removing those value that already exist.

        Required scopes: `list_entry:read-write`, `list_configuration:read`.
      tags:
      - Entries
      security:
      - oauth2:
        - list_entry:read-write
        - list_configuration:read
    delete:
      summary: Delete a list entry
      description: |-
        Deletes a single list entry by its `entry_id`.

        Required scopes: `list_entry:read-write`, `list_configuration:read`.
      tags:
      - Entries
      security:
      - oauth2:
        - list_entry:read-write
        - list_configuration:read
  "/v2/lists/{list}/entries/{entry_id}/attributes/{attribute}/values":
    get:
      summary: List attribute values for a list entry
      description: |-
        Gets all values for a given attribute on a list entry. If the attribute is historic, this endpoint has the ability to return all historic values using the `show_historic` query param.

        Required scopes: `list_entry:read`, `list_configuration:read`.
      tags:
      - Entries
      security:
      - oauth2:
        - list_entry:read
        - list_configuration:read
  "/v2/workspace_members":
    get:
      summary: List workspace members
      description: |-
        Lists all workspace members in the workspace.

        Required scopes: `user_management:read`.
      tags:
      - Workspace members
      security:
      - oauth2:
        - user_management:read
  "/v2/workspace_members/{workspace_member_id}":
    get:
      summary: Get a workspace member
      description: |-
        Gets a single workspace member by ID.

        Required scopes: `user_management:read`.
      tags:
      - Workspace members
      security:
      - oauth2:
        - user_management:read
  "/v2/notes":
    get:
      summary: List notes
      description: |-
        List notes for all records or for a specific record.

        Required scopes: `note:read`, `object_configuration:read`, `record_permission:read`.
      tags:
      - Notes
      security:
      - oauth2:
        - note:read
        - object_configuration:read
        - record_permission:read
    post:
      summary: Create a note
      description: |-
        Creates a new note for a given record.

        At present, notes can only be created from plaintext without formatting.

        Required scopes: `note:read-write`, `object_configuration:read`, `record_permission:read`.
      tags:
      - Notes
      security:
      - oauth2:
        - note:read-write
        - object_configuration:read
        - record_permission:read
  "/v2/notes/{note_id}":
    get:
      summary: Get a note
      description: |-
        Get a single note by ID.

        Required scopes: `note:read`, `object_configuration:read`, `record_permission:read`.
      tags:
      - Notes
      security:
      - oauth2:
        - note:read
        - object_configuration:read
        - record_permission:read
    delete:
      summary: Delete a note
      description: |-
        Delete a single note by ID.

        Required scopes: `note:read-write`.
      tags:
      - Notes
      security:
      - oauth2:
        - note:read-write
  "/v2/tasks":
    get:
      summary: List tasks
      description: |-
        List all tasks. Results are sorted by creation date, from oldest to newest.

        Required scopes: `task:read`, `object_configuration:read`, `record_permission:read`, `user_management:read`.
      tags:
      - Tasks
      security:
      - oauth2:
        - task:read
        - object_configuration:read
        - record_permission:read
        - user_management:read
    post:
      summary: Create a task
      description: |-
        Creates a new task.

        At present, tasks can only be created from plaintext without record reference formatting.

        Required scopes: `task:read-write`, `object_configuration:read`, `record_permission:read`, `user_management:read`.
      tags:
      - Tasks
      security:
      - oauth2:
        - task:read-write
        - object_configuration:read
        - record_permission:read
        - user_management:read
  "/v2/tasks/{task_id}":
    get:
      summary: Get a task
      description: |-
        Get a single task by ID.

        Required scopes: `task:read`, `object_configuration:read`, `record_permission:read`, `user_management:read`.
      tags:
      - Tasks
      security:
      - oauth2:
        - task:read
        - object_configuration:read
        - record_permission:read
        - user_management:read
    patch:
      summary: Update a task
      description: |-
        Updates an existing task by `task_id`. At present, only the `deadline_at`, `is_completed`, `linked_records`, and `assignees` fields can be updated.

        Required scopes: `task:read-write`, `object_configuration:read`, `record_permission:read`, `user_management:read`.
      tags:
      - Tasks
      security:
      - oauth2:
        - task:read-write
        - object_configuration:read
        - record_permission:read
        - user_management:read
    delete:
      summary: Delete a task
      description: |-
        Delete a task by ID.

        Required scopes: `task:read-write`.
      tags:
      - Tasks
      security:
      - oauth2:
        - task:read-write
  "/v2/threads":
    get:
      summary: List threads
      description: |-
        List threads of comments on a record or list entry.

        To view threads on records, you will need the `object_configuration:read` and `record_permission:read` scopes.

        To view threads on list entries, you will need the `list_configuration:read` and `list_entry:read` scopes.

        Required scopes: `comment:read`.
      tags:
      - Threads
      security:
      - oauth2:
        - comment:read
  "/v2/threads/{thread_id}":
    get:
      summary: Get a thread
      description: |-
        Get all comments in a thread.

        To view threads on records, you will need the `object_configuration:read` and `record_permission:read` scopes.

        To view threads on list entries, you will need the `list_configuration:read` and `list_entry:read` scopes.

        Required scopes: `comment:read`.
      tags:
      - Threads
      security:
      - oauth2:
        - comment:read
  "/v2/comments":
    post:
      summary: Create a comment
      description: |-
        Creates a new comment related to an existing thread, record or entry.

        To create comments on records, you will need the `object_configuration:read` and `record_permission:read` scopes.

        To create comments on list entries, you will need the `list_configuration:read` and `list_entry:read` scopes.

        Required scopes: `comment:read-write`.
      tags:
      - Comments
      security:
      - oauth2:
        - comment:read-write
  "/v2/comments/{comment_id}":
    get:
      summary: Get a comment
      description: |-
        Get a single comment by ID.

        To view comments on records, you will need the `object_configuration:read` and `record_permission:read` scopes.

        To view comments on list entries, you will need the `list_configuration:read` and `list_entry:read` scopes.

        Required scopes: `comment:read`.
      tags:
      - Comments
      security:
      - oauth2:
        - comment:read
    delete:
      summary: Delete a comment
      description: |-
        Deletes a comment by ID. If deleting a comment at the head of a thread, all messages in the thread are also deleted.

        Required scopes: `comment:read-write`.
      tags:
      - Comments
      security:
      - oauth2:
        - comment:read-write
  "/v2/webhooks":
    get:
      summary: List webhooks
      description: |-
        Get all of the webhooks in your workspace.

        Required scopes: `webhook:read`.
      tags:
      - Webhooks
      security:
      - oauth2:
        - webhook:read
    post:
      summary: Create a webhook
      description: |-
        Create a webhook and associated subscriptions.

        Required scopes: `webhook:read-write`.
      tags:
      - Webhooks
      security:
      - oauth2:
        - webhook:read-write
  "/v2/webhooks/{webhook_id}":
    get:
      summary: Get a webhook
      description: |-
        Get a single webhook.

        Required scopes: `webhook:read`.
      tags:
      - Webhooks
      security:
      - oauth2:
        - webhook:read
    patch:
      summary: Update a webhook
      description: |-
        Update a webhook and associated subscriptions.

        Required scopes: `webhook:read-write`.
      tags:
      - Webhooks
      security:
      - oauth2:
        - webhook:read-write
    delete:
      summary: Delete a webhook
      description: |-
        Delete a webhook by ID.

        Required scopes: `webhook:read-write`.
      tags:
      - Webhooks
      security:
      - oauth2:
        - webhook:read-write
  "/v2/self":
    get:
      summary: Identify
      description: Identify the current access token, the workspace it is linked to,
        and any permissions it has.
      tags:
      - Meta
webhooks: {}