openapi: 3.0.1
info:
  title: airportsapi
  description: Get name and website-URL for airports by ICAO code. Covered airports
    are mostly in Germany.
  version: v1
servers:
- url: https://airport-web.appspot.com/_ah/api
paths:
  /airportsapi/v1/airports/{icao_code}:
    get:
      operationId: AirportApi_getAirport
      parameters:
      - name: icao_code
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiEndpointsAirportResponse'
components:
  schemas:
    ApiEndpointsAirportResponse:
      type: object
      properties:
        ICAO:
          type: string
        last_update:
          type: string
        name:
          type: string
        url:
          type: string
  securitySchemes:
    google_id_token:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: ""
          scopes: {}
      x-google-issuer: accounts.google.com
      x-google-jwks_uri: https://www.googleapis.com/oauth2/v1/certs
x-original-swagger-version: "2.0"
