openapi: 3.0.1
info:
  title: API title
  version: 0.0.1
servers:
- url: //www.refugerestrooms.org/api
tags:
- name: restrooms
  description: Operations about restrooms
paths:
  /v1/restrooms/by_date:
    get:
      tags:
      - restrooms
      description: Search for restroom records updated or created on or after a given
        date
      operationId: getV1RestroomsByDate
      parameters:
      - name: page
        in: query
        description: Page offset to fetch.
        schema:
          type: integer
          format: int32
          default: 1
      - name: per_page
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
          format: int32
          default: 10
      - name: offset
        in: query
        description: Pad a number of results.
        schema:
          type: integer
          format: int32
          default: 0
      - name: ada
        in: query
        description: Only return restrooms that are ADA accessible.
        schema:
          type: boolean
      - name: unisex
        in: query
        description: Only return restrooms that are unisex.
        schema:
          type: boolean
      - name: updated
        in: query
        description: Return restroom records updated (rather than created) since given
          date
        schema:
          type: boolean
      - name: day
        in: query
        description: Day
        required: true
        schema:
          type: integer
          format: int32
      - name: month
        in: query
        description: Month
        required: true
        schema:
          type: integer
          format: int32
      - name: year
        in: query
        description: Year
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: Search for restroom records updated or created on or after
            a given date
          content: {}
  /v1/restrooms/by_location:
    get:
      tags:
      - restrooms
      description: Search by location.
      operationId: getV1RestroomsByLocation
      parameters:
      - name: page
        in: query
        description: Page offset to fetch.
        schema:
          type: integer
          format: int32
          default: 1
      - name: per_page
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
          format: int32
          default: 10
      - name: offset
        in: query
        description: Pad a number of results.
        schema:
          type: integer
          format: int32
          default: 0
      - name: ada
        in: query
        description: Only return restrooms that are ADA accessible.
        schema:
          type: boolean
      - name: unisex
        in: query
        description: Only return restrooms that are unisex.
        schema:
          type: boolean
      - name: lat
        in: query
        description: latitude
        required: true
        schema:
          type: number
          format: float
      - name: lng
        in: query
        description: longitude
        required: true
        schema:
          type: number
          format: float
      responses:
        "200":
          description: Search by location.
          content: {}
  /v1/restrooms/search:
    get:
      tags:
      - restrooms
      description: Perform full-text search of restroom records.
      operationId: getV1RestroomsSearch
      parameters:
      - name: page
        in: query
        description: Page offset to fetch.
        schema:
          type: integer
          format: int32
          default: 1
      - name: per_page
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
          format: int32
          default: 10
      - name: offset
        in: query
        description: Pad a number of results.
        schema:
          type: integer
          format: int32
          default: 0
      - name: ada
        in: query
        description: Only return restrooms that are ADA accessible.
        schema:
          type: boolean
      - name: unisex
        in: query
        description: Only return restrooms that are unisex.
        schema:
          type: boolean
      - name: query
        in: query
        description: Your search query.
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Perform full-text search of restroom records.
          content: {}
  /v1/restrooms:
    get:
      tags:
      - restrooms
      description: Get all restroom records ordered by date descending.
      operationId: getV1Restrooms
      parameters:
      - name: page
        in: query
        description: Page offset to fetch.
        schema:
          type: integer
          format: int32
          default: 1
      - name: per_page
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
          format: int32
          default: 10
      - name: offset
        in: query
        description: Pad a number of results.
        schema:
          type: integer
          format: int32
          default: 0
      - name: ada
        in: query
        description: Only return restrooms that are ADA accessible.
        schema:
          type: boolean
      - name: unisex
        in: query
        description: Only return restrooms that are unisex.
        schema:
          type: boolean
      responses:
        "200":
          description: Get all restroom records ordered by date descending.
          content: {}
components: {}
x-original-swagger-version: "2.0"
