openapi: 3.0.1
info:
  title: Swagger Generator
  description: "This is an online swagger codegen server.  You can find out more at\
    \ https://github.com/swagger-api/swagger-codegen or on [irc.freenode.net, #swagger](http://swagger.io/irc/)."
  termsOfService: http://swagger.io/terms/
  contact:
    name: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 2.4.31
  x-apisguru-categories:
  - developer_tools
  - tools
  x-logo:
    backgroundColor: '#98C600'
    url: https://twitter.com/SwaggerApi/profile_image?size=original
  x-origin:
  - format: swagger
    url: https://generator.swagger.io/api/swagger.json
    version: "2.0"
  x-providerName: swagger.io
  x-serviceName: generator
servers:
- url: https://generator.swagger.io/api
tags:
- name: gen
- name: clients
- name: servers
paths:
  /gen/clients:
    get:
      tags:
      - clients
      summary: Gets languages supported by the client generator
      operationId: clientOptions
      responses:
        "200":
          description: successful operation
          content:
            '*/*':
              schema:
                type: array
                items:
                  type: string
  /gen/clients/{language}:
    get:
      tags:
      - clients
      summary: Returns options for a client library
      operationId: getClientOptions
      parameters:
      - name: language
        in: path
        description: The target language for the client library
        required: true
        schema:
          type: string
          enum:
          - ada
          - akka-scala
          - android
          - apex
          - bash
          - clojure
          - cpprest
          - csharp
          - csharp-dotnet2
          - cwiki
          - dart
          - dart-jaguar
          - dynamic-html
          - eiffel
          - elixir
          - elm
          - erlang-client
          - flash
          - go
          - groovy
          - haskell-http-client
          - html
          - html2
          - java
          - javascript
          - javascript-closure-angular
          - jaxrs-cxf-client
          - jmeter
          - kotlin
          - lua
          - objc
          - perl
          - php
          - powershell
          - python
          - qt5cpp
          - r
          - ruby
          - rust
          - scala
          - scalaz
          - swagger
          - swagger-yaml
          - swift
          - swift3
          - swift4
          - swift5
          - tizen
          - typescript-angular
          - typescript-angularjs
          - typescript-aurelia
          - typescript-fetch
          - typescript-inversify
          - typescript-jquery
          - typescript-node
          - ue4cpp
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  $ref: '#/components/schemas/CliOption'
    post:
      tags:
      - clients
      summary: Generates a client library
      description: Accepts a `GeneratorInput` options map for spec location and generation
        options
      operationId: generateClient
      parameters:
      - name: language
        in: path
        description: The target language for the client library
        required: true
        schema:
          type: string
          enum:
          - ada
          - akka-scala
          - android
          - apex
          - bash
          - clojure
          - cpprest
          - csharp
          - csharp-dotnet2
          - cwiki
          - dart
          - dart-jaguar
          - dynamic-html
          - eiffel
          - elixir
          - elm
          - erlang-client
          - flash
          - go
          - groovy
          - haskell-http-client
          - html
          - html2
          - java
          - javascript
          - javascript-closure-angular
          - jaxrs-cxf-client
          - jmeter
          - kotlin
          - lua
          - objc
          - perl
          - php
          - powershell
          - python
          - qt5cpp
          - r
          - ruby
          - rust
          - scala
          - scalaz
          - swagger
          - swagger-yaml
          - swift
          - swift3
          - swift4
          - swift5
          - tizen
          - typescript-angular
          - typescript-angularjs
          - typescript-aurelia
          - typescript-fetch
          - typescript-inversify
          - typescript-jquery
          - typescript-node
          - ue4cpp
      requestBody:
        description: Configuration for building the client library
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/GeneratorInput'
        required: true
      responses:
        "200":
          description: successful operation
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseCode'
      x-codegen-request-body-name: body
  /gen/download/{fileId}:
    get:
      tags:
      - clients
      - servers
      summary: Downloads a pre-generated file
      description: "A valid `fileId` is generated by the `/clients/{language}` or\
        \ `/servers/{language}` POST operations.  The fileId code can be used just\
        \ once, after which a new `fileId` will need to be requested."
      operationId: downloadFile
      parameters:
      - name: fileId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            application/octet-stream:
              schema:
                type: string
  /gen/servers:
    get:
      tags:
      - servers
      summary: Gets languages supported by the server generator
      operationId: serverOptions
      responses:
        "200":
          description: successful operation
          content:
            '*/*':
              schema:
                type: array
                items:
                  type: string
  /gen/servers/{framework}:
    get:
      tags:
      - servers
      summary: Returns options for a server framework
      operationId: getServerOptions
      parameters:
      - name: framework
        in: path
        description: The target language for the server framework
        required: true
        schema:
          type: string
          enum:
          - ada-server
          - aspnetcore
          - erlang-server
          - finch
          - go-server
          - haskell
          - inflector
          - java-pkmst
          - java-play-framework
          - java-vertx
          - jaxrs
          - jaxrs-cxf
          - jaxrs-cxf-cdi
          - jaxrs-resteasy
          - jaxrs-resteasy-eap
          - jaxrs-spec
          - kotlin-server
          - lumen
          - msf4j
          - nancyfx
          - nodejs-server
          - php-silex
          - php-symfony
          - pistache-server
          - python-flask
          - rails5
          - restbed
          - rust-server
          - scala-lagom-server
          - scalatra
          - sinatra
          - slim
          - spring
          - undertow
          - ze-ph
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  $ref: '#/components/schemas/CliOption'
    post:
      tags:
      - servers
      summary: Generates a server library
      description: Accepts a `GeneratorInput` options map for spec location and generation
        options.
      operationId: generateServerForLanguage
      parameters:
      - name: framework
        in: path
        description: framework
        required: true
        schema:
          type: string
          enum:
          - ada-server
          - aspnetcore
          - erlang-server
          - finch
          - go-server
          - haskell
          - inflector
          - java-pkmst
          - java-play-framework
          - java-vertx
          - jaxrs
          - jaxrs-cxf
          - jaxrs-cxf-cdi
          - jaxrs-resteasy
          - jaxrs-resteasy-eap
          - jaxrs-spec
          - kotlin-server
          - lumen
          - msf4j
          - nancyfx
          - nodejs-server
          - php-silex
          - php-symfony
          - pistache-server
          - python-flask
          - rails5
          - restbed
          - rust-server
          - scala-lagom-server
          - scalatra
          - sinatra
          - slim
          - spring
          - undertow
          - ze-ph
      requestBody:
        description: parameters
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/GeneratorInput'
        required: true
      responses:
        "200":
          description: successful operation
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseCode'
      x-codegen-request-body-name: body
components:
  schemas:
    AuthorizationValue:
      type: object
      properties:
        keyName:
          type: string
        type:
          type: string
        urlMatcher:
          $ref: '#/components/schemas/UrlMatcher'
        value:
          type: string
    CliOption:
      type: object
      properties:
        default:
          type: string
        description:
          type: string
        enum:
          type: object
          additionalProperties:
            type: string
        optionName:
          type: string
        type:
          type: string
          description: Data type is based on the types supported by the JSON-Schema
    GeneratorInput:
      type: object
      properties:
        authorizationValue:
          $ref: '#/components/schemas/AuthorizationValue'
        options:
          type: object
          additionalProperties:
            type: string
        securityDefinition:
          $ref: '#/components/schemas/SecuritySchemeDefinition'
        spec:
          type: object
          properties: {}
        swaggerUrl:
          type: string
          example: http://petstore.swagger.io/v2/swagger.json
        usingFlattenSpec:
          type: boolean
    ResponseCode:
      type: object
      properties:
        code:
          type: string
          description: File download code
          example: d40029be-eda6-4d62-b1ef-d05e2e91a72a
        link:
          type: string
          description: URL for fetching the generated client
          example: http://generator.swagger.io:80/api/gen/download/d40029be-eda6-4d62-b1ef-d05e2e91a72a
    SecuritySchemeDefinition:
      type: object
      properties:
        description:
          type: string
        type:
          type: string
    UrlMatcher:
      type: object
x-original-swagger-version: "2.0"
